/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.24
 * Generated at: 2024-07-15 07:20:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board2;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.SQLException;
import board2.BoardDTO2;
import board2.BoardDAO2;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Connection;

public final class content_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("java.sql.SQLException");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("board2.BoardDTO2");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("board2.BoardDAO2");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>board2/content.jsp</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/table.css?after\">\r\n");

String id = "";
if (session.getAttribute("id") != null && !session.getAttribute("id").equals("")) {
	id = (String) session.getAttribute("id");
}

      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<h1>board2/content.jsp</h1>\r\n");
      out.write("	");

	int num = Integer.parseInt(request.getParameter("num"));

		BoardDAO2 boardDAO = new BoardDAO2();
		BoardDTO2 board = null;
		try{
			board = boardDAO.getBoard(num);
		}catch(SQLException e){
			e.printStackTrace();
		}

		if (board != null) {
			board.setReadcount(board.getReadcount() + 1);
			String file = board.getFile();
	
      out.write("\r\n");
      out.write("	<p>\r\n");
      out.write("		로그인 :\r\n");
      out.write("		");
      out.print(id);
      out.write("</p>\r\n");
      out.write("	<table>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>글번호</td>\r\n");
      out.write("			<td>");
      out.print(board.getNum());
      out.write("</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>글쓴이</td>\r\n");
      out.write("			<td>");
      out.print(board.getName());
      out.write("</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>조회수</td>\r\n");
      out.write("			<td>");
      out.print(board.getReadcount());
      out.write("</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>글 작성 날짜</td>\r\n");
      out.write("			<td>");
      out.print(board.getDate());
      out.write("</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>글제목</td>\r\n");
      out.write("			<td>");
      out.print(board.getSubject());
      out.write("</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>글내용</td>\r\n");
      out.write("			<td>");
      out.print(board.getContent().replace("\n", "<br>"));
      out.write("</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		");

		if (file != null) {
		
      out.write("\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>첨부파일</td>\r\n");
      out.write("			<td><a href=\"./storage/");
      out.print(file);
      out.write("\" download>");
      out.print(file);
      out.write("</a>\r\n");
      out.write("			<img src=\"./storage/");
      out.print(file);
      out.write("\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		");

		}
		
      out.write("\r\n");
      out.write("		");

		if (board.getName().equals(id)) {
		
      out.write("\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td><a href=\"list.jsp\" class=\"button btnLightBlue\">글 목록</a></td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<a href=\"update.jsp?num=");
      out.print(num);
      out.write("\" class=\"button btnLightBlue\">글 수정</a> \r\n");
      out.write("				<a href=\"delete.jsp?num=");
      out.print(num);
      out.write("\" class=\"button btnLightBlue\">글 삭제</a>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		");

		} else {
		
      out.write("\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td colspan=\"2\"><a href=\"list.jsp\" class=\"button btnLightBlue\">글\r\n");
      out.write("					목록</a></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("\r\n");
      out.write("		");

		}// if id
		
      out.write("\r\n");
      out.write("	</table>\r\n");
      out.write("	");

	boardDAO.updateReadCount(board.getReadcount(), num);
	} //if
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
